kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: sock-shop
  name: stresscpu.handler
spec:
  selector:
    namespaces:
      - sock-shop
    labelSelectors:
      name: catalogue
  mode: all
  stressors:
    cpu:
      workers: 20
      load: 100
  duration: 120s